import 'package:get/get.dart';

class LocalString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys =>
      {
        'en_US':{
          'Home':'Home',
          'Pay' :'Pay',
          'Charge' :'Charge',
          'History':'History',
          'Gift/Coupon':'Gift/Coupon',
          'Intro sercive':'Intro sercive',
          'Franchisee':'Franchisee',
          "My Page":"My Page",
          "More":"More",
          "Remaining Time":"Remaining Time",
          "Paying by GiftCard":"Paying by GiftCard",
          "Confirm":"Confirm",
          "Buying GiftCard":"Buying GiftCard",
          "Paying by ZeroPay":"Paying by ZeroPay",
          "Amount of GiftCard : " :"Amount of GiftCard : ",
          "Please enter 6 digits pass" : "Please enter 6 digits pass",
          "Show the generated QR code to the clerk":"Show the generated QR code to the clerk",
          "Gangwon GiftCard": "Gangwon GiftCard",
          "Monthly Remaining Discount Limit":"Monthly Remaining Discount Limit",
          "discount limit" : "discount limit",
          "Buying":"Buying",
          "Find a franchise":"Find a franchise",
          "Gangwon-do":"Gangwon-do",
          "Search a Shop": "Search a Shop",
          "Distance order":"Distance order",
          "Hanlym Bank":"Hanlym Bank",
          "GiftCard":"GiftCard",
          "ZeroPay":"ZeroPay",
          "Back Coffee Shop":"Back Coffee Shop",
          "Restaurant/café":"Restaurant/café",
          "Bookmark":"Bookmark",
          "Entire GiftCard":"Entire GiftCard",
          "Purchase":"Purchase",
          "Log out":"Log out",
          "Cancel my Membership":"Cancel my Membership",
          "version":"version",
          "Customer Service":"Customer Service",
          "My account":"My account",
          "My info":"My info",
          "My page":"My page",
          "NH bank":"NH bank",
          "main account":"main account",
          "IBK bank":"IBK bank",
          "Set up as main account":"Set up as main account",
          "Delete":"Delete",
          "Name":"Name",
          "Lee Min Hoo":"Lee Min Hoo",
          "Email":"Email",
          "Phone num":"Phone num",
          "Edit my info":"Edit my info",
          "Change Password":"Change Password"





        },
        'ko_KR':{
          'Home':'홈',
          'Pay' :'결제',
          'Charge':'충전',
          'History':'녀역',
          'Gift/Coupon':'선물/쿠폰',
          'Intro sercive':'서비스 소개',
          'Franchisee':'가맹점',
          "My Page":"내 정보",
          "More":"더보기",
          "Remaining Time":"남은시간",
          "Paying by GiftCard":"상품권 결제",
          "Confirm":"확인",
          "Buying GiftCard":"상품권 구매",
          "Paying by ZeroPay":"제로페이 결제",
          "Amount of GiftCard : " :"상품권 사용 가능 금액 : ",
          "Please enter 6 digits pass" : "거래승인번호 6자리를 입력해주세요",
          "Show the generated QR code to the clerk":"생성된 QR코드를 점원에게 보여주세요",
          "Gangwon GiftCard": "강원상품권",
          "Monthly Remaining Discount Limit":"월 잔여 할인 한도",
          "discount limit" : "할인한도",
          "Buying":"구매하기",
          "Find a franchise":"가맹점찾기",
          "Gangwon-do":"강원도",
          "Search a Shop": "매장검색",
          "Distance order":"거리순",
          "Hanlym Bank":"한림 은행",
          "GiftCard":"상품권",
          "ZeroPay":"제로페이",
          "Back Coffee Shop":"빽다방",
          "Restaurant/café":"음식점/카페",
          "Bookmark":"즐겨찾기",
          "Entire GiftCard":"전체 상품권",
          "Purchase":"구매",
          "Log out":"로그아웃",
          "Cancel my Membership":"회원 탈퇴",
          "version":"버전",
          "Customer Service":"고객센터",
          "My account":"내 계좌",
          "My info":"내 정보",
          "My page":"마이 페이지",
          "NH bank":"농협은행",
          "main account":"주계과",
          "IBK bank":"기업은행",
          "Set up as main account":"주계좌 설정",
          "Delete":"삭제",
          "Name":"이름",
          "Lee Min Hoo":"이민호",
          "Email":"이메일",
          "Phone num":"천화번호",
          "Edit my info":"회원정보 변경",
          "Change Password":"비밀번호 변경"


        }
      };

}